# Generated by Django 4.1.2 on 2022-12-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogshlogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Blog',
        ),
    ]
